function advance_types = get_advance_types()

    advance_types = {'solveonestep'                       , ...
                    'solveonestep_linear'                 , ...
                    'nonlinear_explicit'                  , ...
                    'ANN'                                 , ...
                    'linear_CN_uaffine'                   , ...
                    'linear_advance'                      , ...
                    'linear_advance_timeexplicit'         , ...
                    'linear_advance_uaffine'              , ...
                    'linear_advance_timeexplicit_uaffine' };

end